env WEB_PAGE_COLOR;

events {}

http {
  server {
    listen 80;

    sub_filter_types text/html;

    location / {
      root /usr/share/nginx/html;
      index index.html;
      sub_filter '__WEB_PAGE_COLOR__' '$WEB_PAGE_COLOR';
      sub_filter_once on;
    }

    # proxy /api/* to the api container
    location /api/ {
      proxy_pass http://api:8000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
